---

pipeline:
  dependencies:
    image: node:alpine
    commands:
      - yarn
  tests:
    image: node:alpine
    commands:
      - yarn test
  build:
    image: node:alpine
    commands:
      - yarn build
      - tar -zcvf build.tar.gz -C build .
    when:
      event: tag
  release:
    image: plugins/github-release
    api_key: <github_api_key>
    files:
      - build.tar.gz
   checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
    secrets: [ github_api_key ]
  notify:
    image: plugins/slack
    webhook: <slack_webhook>
    channel: drone
    secrets: [ slack_webhook ]
    username: nadine_morano
    image_url: https://unsplash.it/256/256/?random
    template: >
      {{#success build.status}}
        La belle build {{build.number}} a fonctionné. GG.
      {{else}}
        La build {{build.number}} a raté. Nul. Fix-moi ça.
      {{/success}}
